# Generated by Django 2.1.7 on 2019-04-12 09:30

from django.db import migrations
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0089_auto_20190225_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=django_prices.models.MoneyField(currency='USD', decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
