# Generated by Django 2.1.7 on 2019-04-12 12:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0091_auto_20190412_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, max_length=350),
        ),
    ]
