# Generated by Django 2.1.7 on 2019-04-12 12:39

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0092_auto_20190412_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='seo_description',
            field=models.CharField(blank=True, max_length=350, null=True, validators=[django.core.validators.MaxLengthValidator(350)]),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='seo_description',
            field=models.CharField(blank=True, max_length=350, null=True, validators=[django.core.validators.MaxLengthValidator(350)]),
        ),
        migrations.AlterField(
            model_name='collection',
            name='seo_description',
            field=models.CharField(blank=True, max_length=350, null=True, validators=[django.core.validators.MaxLengthValidator(350)]),
        ),
        migrations.AlterField(
            model_name='collectiontranslation',
            name='seo_description',
            field=models.CharField(blank=True, max_length=350, null=True, validators=[django.core.validators.MaxLengthValidator(350)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, max_length=350, null=True, validators=[django.core.validators.MaxLengthValidator(350)]),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='seo_description',
            field=models.CharField(blank=True, max_length=350, null=True, validators=[django.core.validators.MaxLengthValidator(350)]),
        ),
    ]
