# Generated by Django 2.1.7 on 2019-04-12 12:51

import django.core.validators
from django.db import migrations, models
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0093_auto_20190412_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='seo_description',
            field=models.CharField(blank=True, max_length=430, null=True, validators=[django.core.validators.MaxLengthValidator(430)]),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='seo_description',
            field=models.CharField(blank=True, max_length=430, null=True, validators=[django.core.validators.MaxLengthValidator(430)]),
        ),
        migrations.AlterField(
            model_name='collection',
            name='seo_description',
            field=models.CharField(blank=True, max_length=430, null=True, validators=[django.core.validators.MaxLengthValidator(430)]),
        ),
        migrations.AlterField(
            model_name='collectiontranslation',
            name='seo_description',
            field=models.CharField(blank=True, max_length=430, null=True, validators=[django.core.validators.MaxLengthValidator(430)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=django_prices.models.MoneyField(currency='EUR', decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, max_length=430, null=True, validators=[django.core.validators.MaxLengthValidator(430)]),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='seo_description',
            field=models.CharField(blank=True, max_length=430, null=True, validators=[django.core.validators.MaxLengthValidator(430)]),
        ),
    ]
