# Generated by Django 2.1.7 on 2019-04-22 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0098_auto_20190422_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytranslation',
            name='seo_description',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='collectiontranslation',
            name='seo_description',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='seo_description',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
