# Generated by Django 2.1.7 on 2019-04-25 06:46

from django.db import migrations
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0100_auto_20190422_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=django_prices.models.MoneyField(currency='PLN', decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
