# Generated by Django 2.1.7 on 2019-06-13 12:33

import django.core.validators
from django.db import migrations, models
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0101_auto_20190425_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='seo_description',
            field=models.CharField(blank=True, max_length=600, null=True, validators=[django.core.validators.MaxLengthValidator(600)]),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='seo_description',
            field=models.CharField(blank=True, max_length=600, null=True, validators=[django.core.validators.MaxLengthValidator(600)]),
        ),
        migrations.AlterField(
            model_name='collection',
            name='seo_description',
            field=models.CharField(blank=True, max_length=600, null=True, validators=[django.core.validators.MaxLengthValidator(600)]),
        ),
        migrations.AlterField(
            model_name='collectiontranslation',
            name='seo_description',
            field=models.CharField(blank=True, max_length=600, null=True, validators=[django.core.validators.MaxLengthValidator(600)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=django_prices.models.MoneyField(currency='UAH', decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, max_length=600, null=True, validators=[django.core.validators.MaxLengthValidator(600)]),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='seo_description',
            field=models.CharField(blank=True, max_length=600, null=True, validators=[django.core.validators.MaxLengthValidator(600)]),
        ),
    ]
