# Generated by Django 2.1.7 on 2019-04-12 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20190412_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='seo_description',
            field=models.CharField(blank=True, max_length=430, null=True, validators=[django.core.validators.MaxLengthValidator(430)]),
        ),
        migrations.AlterField(
            model_name='pagetranslation',
            name='seo_description',
            field=models.CharField(blank=True, max_length=430, null=True, validators=[django.core.validators.MaxLengthValidator(430)]),
        ),
    ]
