# Generated by Django 2.1.7 on 2019-04-22 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_auto_20190412_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetranslation',
            name='seo_title',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
