# Generated by Django 2.1.7 on 2019-04-22 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_auto_20190422_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetranslation',
            name='seo_description',
            field=models.CharField(blank=True, max_length=450, null=True, validators=[django.core.validators.MaxLengthValidator(450)]),
        ),
    ]
