# Generated by Django 2.1.7 on 2019-06-13 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_auto_20190422_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='seo_description',
            field=models.CharField(blank=True, max_length=600, null=True, validators=[django.core.validators.MaxLengthValidator(600)]),
        ),
        migrations.AlterField(
            model_name='pagetranslation',
            name='seo_description',
            field=models.CharField(blank=True, max_length=600, null=True, validators=[django.core.validators.MaxLengthValidator(600)]),
        ),
    ]
